app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(template_name='app/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('@<str:username>/', views.bus, name='bus'),
    path('u/<str:username>/', views.profile, name='profile'),
    path('edit/', views.edit, name='edit'),
    path('@<str:username>/follow/', views.follow, name='follow'),
    path('about/start/register/', views.registerb, name='registerb'),
    path('about/start/', views.startb, name='startb'),
    path('@<str:username>/report/', views.report, name='report'),
    path('about/staff/', views.staff, name='staff'),
    path('@<str:username>/block/', views.block, name='block'),
    path('about/', views.about, name='about'),
]

chat/urls.py
from django.urls import path
from .views import InboxView, UserListsView, MessagesListView, report

app_name = 'chat'

urlpatterns = [
    path('', MessagesListView.as_view(), name='message_list'),
    path('u/', UserListsView.as_view(), name='users_list'),
    path('u/<str:username>/', InboxView.as_view(), name='inbox'),
    path('u/<str:username>/report/', report, name='report'),
]

hexagon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('chat/', include('chat.urls')),
    path('', include('post.urls')),
    path('staff/', include('staff.urls')),
    path('verification/', include('verify_email.urls')),
    path('notifications/', include('notifications.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from app.models import rename_image

# The Message class defines a model for storing messages between users and includes methods for
# retrieving and displaying messages.
class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recipient')
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)
    is_system = models.BooleanField(default=False)
    image = models.ImageField(blank=True, null=True, upload_to=rename_image)

    def __str__(self):
        """
        This function returns the message attribute of an object as a string.
        :return: The `__str__` method is returning the `message` attribute of the object.
        """
        return self.message

    # The class defines metadata for a database table called "chat_messages" including verbose names
    # and ordering.
    class Meta:
        db_table = 'chat_messages'
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'
        ordering = ('-date',)

    def get_all_messages(id_1, id_2):
        """
        This function retrieves all messages between two users and marks them as read for the first
        user.
        
        :param id_1: The ID of the first user in the conversation
        :param id_2: The parameter `id_2` is likely an identifier for the recipient of the messages. It
        is used in the function to filter messages where the sender is `id_1` and the recipient is
        `id_2`, and also to filter messages where the sender is `id_2` and
        :return: The function `get_all_messages` returns a list of messages between two users with the
        given `id_1` and `id_2`. The messages are sorted by date in ascending order. If `id_1` is not
        equal to `id_2`, the function also includes messages sent from `id_2` to `id_1`. The function
        also marks all messages sent from
        """
        messages = []
        message1 = Message.objects.filter(sender_id=id_1, recipient_id=id_2).order_by('-date')
        for x in range(len(message1)):
            message1[x].is_read = True
            message1[x].save()
            messages.append(message1[x])
        if id_1 != id_2:
            message2 = Message.objects.filter(sender_id=id_2, recipient_id=id_1).order_by('-date')
            for x in range(len(message2)):
                messages.append(message2[x])
        messages.sort(key=lambda x: x.date, reverse=False)
        return messages

    def get_message_list(u):
        """
        This function retrieves a list of messages for a given user, sorted by sender and date, and
        removes duplicates.
        
        :param u: The parameter "u" is likely a user object representing the user for whom we want to
        retrieve a list of messages
        :return: The function `get_message_list(u)` returns a list of messages that involve the user
        `u`. The messages are sorted by sender's username and then by date in descending order. The
        function also removes duplicate messages and returns only one message per conversation between
        two users.
        """
        m = []
        j = []
        k = []
        for message in Message.objects.all():
            for_you = message.recipient == u
            from_you = message.sender == u
            if (for_you != from_you) and (for_you or from_you):
                m.append(message)
                m.sort(key=lambda x: x.sender.username)
                m.sort(key=lambda x: x.date, reverse=True)
        for i in m:
            if i.sender.username not in j or i.recipient.username not in j:
                j.append(i.sender.username)
                j.append(i.recipient.username)
                k.append(i)
        return k

chat/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Message
from django.contrib.auth.models import User
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from staff.models import ReChat
from notifications.views import message as notify
from django.contrib.auth.decorators import login_required

INBOX = 'chat:inbox'

# This is a class that displays a list of messages and other users in a chat application.
class MessagesListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = 'chat/messages_list.html'

    def get_context_data(self, **kwargs):
        """
        This function retrieves message data and other user data to be displayed in a context
        dictionary.
        :return: This code is a method that returns a dictionary of context data to be used in a Django
        template. The context data includes a list of messages, a list of other users involved in those
        messages, and the current user.
        """
        context = super().get_context_data(**kwargs)
        user = User.objects.get(pk=self.request.user.pk)
        messages = Message.get_message_list(user)
        other_users = []
        for i in range(len(messages)):
            if messages[i].sender != user:
                other_users.append(messages[i].sender)
            else:
                other_users.append(messages[i].recipient)
        context['messages_list'] = messages
        context['other_users'] = other_users
        context['you'] = user
        return context

# This is a Django class-based view for displaying and handling messages in a user's inbox.
class InboxView(LoginRequiredMixin, DetailView):
    model = Message
    template_name = 'chat/inbox.html'
    queryset = User.objects.all()

    def dispatch(self, request, *args, **kwargs):
        """
        This function overrides the dispatch method of a class and returns the result of calling the
        parent dispatch method with the request and arguments.
        
        :param request: The HTTP request object that contains information about the incoming request,
        such as the HTTP method, headers, and body
        :return: The `dispatch` method of a class is being called with the `request` object, `args`, and
        `kwargs` as arguments. The `super()` function is used to call the `dispatch` method of the
        parent class, and the `self.request` attribute is passed as the first argument to the parent
        method. The return value of the parent `dispatch` method is being returned.
        """
        return super().dispatch(self.request, *args, **kwargs)

    def get_object(self):
        """
        This function retrieves a User object based on the provided username or returns a 404 error if
        the object does not exist.
        :return: The `get_object()` method is returning a `User` object with the `username` specified in
        the URL path. If the user with that `username` does not exist, a 404 error page will be
        returned.
        """
        username= self.kwargs.get("username")
        return get_object_or_404(User, username=username)

    def get_context_data(self, **kwargs):
        """
        This function gets context data for a view, including messages between two users and information
        about those users.
        :return: The `context` dictionary with added keys `'messages'`, `'other_person'`, and `'you'` is
        being returned.
        """
        context = super().get_context_data(**kwargs)
        user = User.objects.get(pk=self.request.user.pk)
        other_user = User.objects.get(username=self.kwargs.get("username"))
        context['messages'] = Message.get_all_messages(other_user, user)
        context['other_person'] = other_user
        context['you'] = user
        return context

    def post(self, request, *args, **kwargs):
        """
        This function handles a POST request to create a new message post with a sender, recipient,
        message, and optional image attachment.
        
        :param request: The HTTP request object that contains information about the current request,
        such as the user making the request, the HTTP method used, and any data submitted with the
        request
        :return: The view is returning a redirect to the `INBOX` view with the `username` parameter set
        to the `username` of the `recipient` user object. If the user is not authenticated, the view is
        rendering the `login.html` template.
        """
        sender = User.objects.get(pk=request.POST.get('you'))
        recipient = User.objects.get(pk=request.POST.get('recipient'))
        message = request.POST.get('message')
        image = request.FILES.get('img')
        if request.user.is_authenticated:
            if request.method == 'POST':
                mkpost(request, sender, recipient, message, image)
            return redirect(INBOX, username=recipient.username)
        else:
            return render(request, 'auth/login.html')

def mkpost(request, sender, recipient, message, image):
    """
    The function sends a message and/or image from a sender to a recipient, but redirects if the
    recipient is blocked by the sender.
    
    :param request: The request object represents the current HTTP request that the user has made to the
    server. It contains information about the user's request, such as the HTTP method used (GET, POST,
    etc.), the URL requested, and any data submitted in the request
    :param sender: The user who is sending the message or post. It is likely an instance of a User model
    in Django or a similar framework
    :param recipient: The username of the user who will receive the message
    :param message: The message parameter is a string that represents the text message that the sender
    wants to send to the recipient
    :param image: The "image" parameter is a variable that holds the image file that the user wants to
    send along with their message. It could be an image file in any format such as JPEG, PNG, or GIF. If
    the user does not want to send an image, this parameter will be set to None
    :return: If the recipient is in the sender's blocking list or blocked list, the function redirects
    to the inbox page of the recipient's username. Otherwise, the function sends a message with the
    given parameters (sender, recipient, message, image) and returns nothing.
    """
    if recipient in sender.profile.blocking() or recipient in sender.profile.blocked():
        return redirect(INBOX, username=recipient.username)
    else:
        if image:
            message = 'Image'
        if message:
            send(request ,sender, recipient, message, image, False)

def send(request, sender, recipient, message, image, system):
    """
    This function sends a message to a recipient and creates a system message if it's the first message
    in the conversation.
    
    :param request: The request object represents the current HTTP request that the user has made to the
    server. It contains information about the user's request, such as the URL, headers, and any data
    that was sent with the request
    :param sender: The user who is sending the message. It is likely an instance of the User model in
    Django
    :param recipient: The user who will receive the message
    :param message: The actual text message that the sender wants to send to the recipient
    :param image: The "image" parameter is likely a variable that holds an image file or URL that the
    sender wants to include in their message. It could be an image of anything, such as a meme, a
    screenshot, or a photo. The function appears to allow for the inclusion of both a text message and
    :param system: The "system" parameter is a boolean value that indicates whether the message being
    sent is a system message or not. If it is a system message, it means that it is not a message sent
    by a user, but rather a message generated by the system itself. This can be useful for notifications
    or
    """
    if not Message.get_all_messages(sender, recipient):
        Message.objects.create(sender=sender, recipient=recipient,
        message=sender.username+
        " has started a conversation with "+
        recipient.username,
        is_system=True)
    Message.objects.create(sender=sender, recipient=recipient, message=message, image=image, is_system=system)
    notify(request, recipient)

# This is a Django class-based view that displays a list of all users in the database on a template
# called 'users_list.html'.
class UserListsView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'chat/users_list.html'
    context_object_name = 'users'

    def get_context_data(self, **kwargs):
        """
        This function adds all users to the context data of a view.
        :return: The `get_context_data` method is returning a dictionary object `context` which contains
        a key-value pair where the key is `'users'` and the value is a queryset of all `User` objects in
        the database. This queryset is obtained using the `all` method on the `User` model.
        """
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.all
        return context

@login_required
def report(request, username):
    """
    This function creates a report for a chat if it doesn't already exist and redirects the user to the
    inbox page.
    
    :param request: The request parameter is an object that represents the HTTP request made by the
    client to the server. It contains information such as the HTTP method used (GET, POST, etc.), the
    headers, the body of the request, and any query parameters. It is typically passed as the first
    parameter to view functions
    :param username: The username parameter is a string that represents the username of a user in the

app/templates/chat/chat.html
{% extends 'app/layout.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/chat.css' %}" />
<div class="container grid">
  {% block contacts %}
  {% endblock contacts %}
  {% block message %}
  {% endblock message %}
</div>
<script src="{% static 'js/chat.js' %}"></script>
{% endblock %}

app/templates/chat/inbox.html
{% extends 'chat/chat.html' %}
{% load humanize %}
{% load urlize_target_blank %}
{% block message %}
<div class="hexagonChat__chat">
  <div class="hexagonChat__chatInfo">
    <i
      class="uil uil-arrow-left hexagonChat__chatIcons_img"
      onclick="location.href='{% url 'chat:message_list' %}'"
    ></i>
    <span
      onclick="location.href='{% url 'bus' other_person %}'"
      style="cursor: pointer"
      >@{{ other_person.username }}
      {% if other_person.is_superuser %}
      <i class="uil uil-polygon"></i>
      {% elif other_person.is_staff %}
      <i class="uil uil-wrench"></i>
      {% elif other_person.profile.business %}
      <i class="uil uil-check-circle"></i>
      {% endif %}
    </span>
    <div class="hexagonChat__chatIcons">
      <i
        class="uil uil-user-plus hexagonChat__chatIcons_img"
        onclick="location.href='{% url 'follow' other_person %}'"
        {% if you not in other_person.profile.followers %}
        title="Follow @{{ other_person }}"
        {% else %}
        title="Unfollow @{{ other_person }}"
        {% endif %}
      ></i>
      <i
        class="uil uil-ellipsis-h hexagonChat__chatIcons_img services__button"
      ></i>
      <div class="services__modal">
        <div class="services__modal-content">
          <h4 class="services__modal-title">
            Chat
            <br />
            settings
          </h4>
          <i class="uil uil-times services__modal-close"></i>

          <ul class="services__modal-services grid">
            <li class="services__modal-service">
              <a
                href="{% url 'block' other_person %}"
                class="button button--flex button--small button--link"
              >
                {% if request.user not in other_person.profile.blocked %}
                Block
                {% else %}
                Unblock
                {% endif %}
              </a>
            </li>
            <li class="services__modal-service">
              <a
                href="{% url 'chat:report' other_person %}"
                class="button button--flex button--small button--link"
              >
                Report
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="hexagonChat__messages" id="chat">
    {% if other_person == you %}
    {% if messages %}
    {% for message in messages %}
    {% if message.is_system %}
    <div class="hexagonChat__messageSystem">
      <p>{{ message.message }}</p>
    </div>
    {% else %}
    <div class="hexagonChat__message hexagonChat__owner">
      <div class="hexagonChat__messageContent">
        <p class="hexagonChat__messageContent_p hexagonChat__owner_p">
          {% if message.image %}
          <img src="{{ message.image.url }}" alt="" class="project__img" />
          {% else %}
          {{ message.message|urlize_target_blank }}
          {% endif %}
          {% if message.is_read %}
          <i class="uil uil-check-circle"></i>
          {% else %}
          <i class="uil uil-check"></i>
          {% endif %}
        </p>
        <span>{{ message.date|naturaltime }}</span>
      </div>
    </div>
    {% endif %}
    {% endfor %}
    {% else %}
    <div class="hexagonChat__messageSystem">
      <p>No messages yet</p>
    </div>
    {% endif %}
    {% else %}
    {% if messages %}
    {% for message in messages %}
    {% if message.is_system %}
    <div class="hexagonChat__messageSystem">
      <p>{{ message.message }}</p>
    </div>
    {% else %}
    {% if message.sender == other_person %}
    <div class="hexagonChat__message">
      <div class="hexagonChat__messageContent">
        <p class="hexagonChat__messageContent_p">
          {% if message.image %}
          <img src="{{ message.image.url }}" alt="" class="project__img" />
          {% else %}
          {{ message.message|urlize_target_blank }}
          {% endif %}
        </p>
        <span>{{ message.date|naturaltime }}</span>
      </div>
    </div>
    {% else %}
    <div class="hexagonChat__message hexagonChat__owner">
      <div class="hexagonChat__messageContent">
        <p class="hexagonChat__messageContent_p hexagonChat__owner_p">
          {% if message.image %}
          <img src="{{ message.image.url }}" alt="" class="project__img" />
          {% else %}
          {{ message.message|urlize_target_blank }}
          {% endif %}
          {% if message.is_read %}
          <i class="uil uil-check-circle"></i>
          {% else %}
          <i class="uil uil-check"></i>
          {% endif %}
        </p>
        <span>{{ message.date|naturaltime }}</span>
      </div>
    </div>
    {% endif %}
    {% endif %}
    {% endfor %}
    {% else %}
    <div class="hexagonChat__messageSystem">
      <p>No messages yet</p>
    </div>
    {% endif %}
    {% endif %}
  </div>
  {% if other_person in you.profile.blocking %}
  {% elif other_person in you.profile.blocked %}
  {% elif request.user.profile.strikes > 1 %}
  {% else %}
  <form
    action="{% url 'chat:inbox' other_person.username %}"
    method="post"
    class="hexagonChat__input"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    <input type="hidden" name="recipient" value="{{ other_person.pk }}" />
    <input type="hidden" name="you" value="{{ you.pk }}" />
    <input
      type="text"
      placeholder="Type something"
      class="hexagonChat__input_input"
      name="message"
    />
    <label class="hexagonChat__input_file">
      <input type="file" name="img" accept="image/*" onchange="previewFile()" />
      <i class="uil uil-image-plus"></i>
    </label>
    <button class="hexagonChat__send_button">Send</button>
  </form>
  {% endif %}
</div>
<div class="services__modal" id="preview_img">
  <div class="services__modal-content">
    <h4 class="services__modal-title">Preview</h4>
    <i class="uil uil-times services__modal-close"></i>
    <ul class="services__modal-services grid">
      <li class="services__modal-service">
        <img src="" alt="" class="project__img" />
      </li>
    </ul>
  </div>
</div>
{% endblock %}

app/templates/chat/messages_list.html
{% extends 'chat/chat.html' %}
{% load humanize %}
{% block contacts %}
<div class="hexagonChat__sidebar">
  <div class="hexagonChat__navbar">
    <span
      class="hexagonChat__logo"
      onclick="location.href='{% url 'chat:message_list' %}'"
      >Chat</span
    >
    <div class="hexagonChat__user">
      <span
        style="cursor: pointer"
        onclick="location.href='{% url 'chat:inbox' request.user %}'"
        >@{{ request.user.username }}</span
      >
    </div>
  </div>
  <div class="hexagonChat__search">
    <div class="hexagonChat__searchForm">
      <div
        class="hexagonChat__searchForm_input"
        onclick="location.href='{% url 'chat:users_list' %}'"
      >
        Find a user
        <i class="uil uil-search"></i>
      </div>
    </div>
  </div>
  <div class="hexagonChat__chats">
    {% for message in messages_list %}
    {% for us in other_users %}
    {% if us in request.user.profile.blocking %}
    {% elif us in request.user.profile.blocked %}
    {% else %}
    {% if us.pk == message.recipient.pk or us.pk == message.sender.pk %}
    <div
      class="hexagonChat__userChat"
      onclick="location.href='{% url 'chat:inbox' us %}'"
    >
      <img class="hexagonChat__userChat_img" src="{{ us.profile.image.url }}" alt="" />
      <div class="hexagonChat__userChatInfo">
        <span class="hexagonChat__userChatInfo_span"
          >{{ us.first_name }}
          {{ us.last_name }}
          {% if us.is_superuser %}
          <i class="uil uil-polygon"></i>
          {% elif us.is_staff %}
          <i class="uil uil-wrench"></i>
          {% elif us.profile.business %}
          <i class="uil uil-check-circle"></i>
          {% endif %}
        </span>
        {% if message.sender == request.user %}
        <p class="hexagonChat__userChatInfo_p">
          {% if message.is_read %}
          <i class="uil uil-check-circle"></i>
          {% else %}
          <i class="uil uil-check"></i>
          {% endif %}
          You: {{ message.message }} - {{ message.date|naturaltime }}
        </p>
        {% else %}
        <p class="hexagonChat__userChatInfo_p">
          {{ us }}: {{ message.message }} - {{ message.date|naturaltime }}
        </p>
        {% endif %}
      </div>
    </div>
    {% endif %}
    {% endif %}
    {% endfor %}
    {% endfor %}
  </div>
</div>
{% endblock %}

app/templates/chat/users_list.html
{% extends 'chat/chat.html' %}
{% block contacts %}
<div class="hexagonChat__sidebar">
  <div class="hexagonChat__navbar">
    <span
      class="hexagonChat__logo"
      onclick="location.href='{% url 'chat:message_list' %}'"
      >Chat</span
    >
    <div class="hexagonChat__user">
      <span>@{{ request.user.username }}</span>
    </div>
  </div>
  <div class="hexagonChat__search">
    <div class="hexagonChat__searchForm">
      <div
        class="hexagonChat__searchForm_input"
        onclick="location.href='{% url 'chat:users_list' %}'"
      >
        Find a user
        <i class="uil uil-search"></i>
      </div>
    </div>
  </div>
  <div class="hexagonChat__chats">
    {% for u in users %}
    {% if u in request.user.profile.blocking %}
    {% elif u in request.user.profile.blocked %}
    {% else %}
    <div
      class="hexagonChat__userChat"
      onclick="location.href='{% url 'chat:inbox' u %}'"
    >
      <img class="hexagonChat__userChat_img" src="{{ u.profile.image.url }}" alt="" />
      <div class="hexagonChat__userChatInfo">
        <span class="hexagonChat__userChatInfo_span"
          >{{ u.first_name }}
          {{ u.last_name }}
          {% if u.is_superuser %}
          <i class="uil uil-polygon"></i>
          {% elif u.is_staff %}
          <i class="uil uil-wrench"></i>
          {% elif u.profile.business %}
          <i class="uil uil-check-circle"></i>
          {% endif %}
        </span>
        <p class="hexagonChat__userChatInfo_p">Hi there!</p>
      </div>
    </div>
    {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}