app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(template_name='app/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('@<str:username>/', views.bus, name='bus'),
    path('u/<str:username>/', views.profile, name='profile'),
    path('edit/', views.edit, name='edit'),
    path('@<str:username>/follow/', views.follow, name='follow'),
    path('about/start/register/', views.registerb, name='registerb'),
    path('about/start/', views.startb, name='startb'),
    path('@<str:username>/report/', views.report, name='report'),
    path('about/staff/', views.staff, name='staff'),
    path('@<str:username>/block/', views.block, name='block'),
    path('about/', views.about, name='about'),
]

chat/urls.py
from django.urls import path
from .views import InboxView, UserListsView, MessagesListView, report

app_name = 'chat'

urlpatterns = [
    path('', MessagesListView.as_view(), name='message_list'),
    path('u/', UserListsView.as_view(), name='users_list'),
    path('u/<str:username>/', InboxView.as_view(), name='inbox'),
    path('u/<str:username>/report/', report, name='report'),
]

hexagon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('chat/', include('chat.urls')),
    path('', include('post.urls')),
    path('staff/', include('staff.urls')),
    path('verification/', include('verify_email.urls')),
    path('notifications/', include('notifications.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('feed/', views.feed, name='feed'),
    path('social/', views.social, name='social'),
    path('feed/<int:offer_id>/delete/', views.odelete, name='odelete'),
    path('social/<int:post_id>/delete/', views.delete, name='delete'),
    path('feed/<int:pk>/like/', views.olike, name='olike'),
    path('social/<int:pk>/like/', views.like, name='like'),
    path('feed/<int:pk>/', views.offer, name='offer'),
    path('social/<int:pk>/', views.post, name='post'),
    path('social/topic/<str:name>', views.topics, name='topic'),
    path('feed/topic/<str:name>', views.otopics, name='otopic'),
    path('social/<int:pk>/report/', views.report, name='report'),
    path('feed/<int:pk>/report/', views.oreport, name='oreport'),
    path('feed/<int:pk>/apply/', views.apply, name='apply'),
]

post/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from app.models import rename_image

# The Offer class defines a model for offers with various fields such as timestamp, head, content,
# user, likes, image, and topics.
class Offer(models.Model):
    timestamp = models.DateTimeField(default=timezone.now)
    head = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='offers')
    likes = models.ManyToManyField(User, blank=True, related_name='olikes')
    is_delete = models.BooleanField(default=False)
    image = models.ImageField(blank=True, null=True, upload_to=rename_image)
    topics = models.ManyToManyField('Topic', blank=True)

    # This class sets the default ordering for a model to be based on the timestamp field in
    # descending order.
    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        """
        This function returns the string representation of the "head" attribute of an object.
        :return: The `__str__` method is returning the value of the `head` attribute of the object. It
        is assumed that `head` is a string attribute.
        """
        return self.head

# This is a Django model class for a post that includes fields for timestamp, content, user, likes,
# comments, deletion status, image, and topics.
class Post(models.Model):
    timestamp = models.DateTimeField(default=timezone.now)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    likes = models.ManyToManyField(User, blank=True, related_name='likes')
    comment = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    is_delete = models.BooleanField(default=False)
    image = models.ImageField(blank=True, null=True, upload_to=rename_image)
    topics = models.ManyToManyField('Topic', blank=True)

    # This class sets the default ordering for a model to be based on the timestamp field in
    # descending order.
    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        """
        This function returns the content of an object as a string.
        :return: The `__str__` method is returning the `content` attribute of the object.
        """
        return self.content

# The Topic class defines a model with a name attribute that can be represented as a string.
class Topic(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        """
        This function returns the name attribute of an object as a string.
        :return: The `__str__` method is returning the `name` attribute of the object.
        """
        return self.name

post/forms.py
from django import forms
from .models import Post, Offer, Topic

# This is a Django form class for creating an Offer object with fields for head, content, and image.
class OfferForm(forms.ModelForm):
    head = forms.CharField(
        widget=forms.TextInput(attrs={
            'maxlength':100,
            'placeholder':"Title"
        })
    )
    content = forms.CharField(
        widget=forms.Textarea(attrs={
            'class':'form-control w-100',
            'id':'contentsBox', 'rows':'3',
            'placeholder':"Body"
        })
    )
    image = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={
            'onchange':'previewFile()'
        })
    )

    # This class defines the model and fields for an Offer object in Python.
    class Meta:
        model = Offer
        fields = ['head', 'content', 'image']

# The `PostForm` class is a Django ModelForm that includes fields for `content` and `image`, with
# corresponding widgets and attributes.
class PostForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(attrs={
            'class':'form-control w-100',
            'id':'contentsBox', 'rows':'3',
            'placeholder':"What's going on?"
        })
    )
    image = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={
            'onchange':'previewFile()'
        })
    )

    # This class defines the model and fields for a Post object.
    class Meta:
        model = Post
        fields = ['content', 'image']

# This is a Django form class for creating or updating a Topic model instance with a single field for
# the name attribute, which is a CharField with optional input validation and a placeholder text.
class TopicForm(forms.ModelForm):
    name = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'maxlength':100,
            'placeholder':"topic1 topic2"
        })
    )

    # This class defines the model and fields for a Topic in Python.
    class Meta:
        model = Topic
        fields = ['name']

post/views.py
from django.shortcuts import render, redirect
from .forms import PostForm, OfferForm, TopicForm
from .models import Post, Offer, Topic
from django.contrib.auth.decorators import login_required
from staff.models import RePost, ReOffer
from notifications.views import post as notify, offer as onotify, comment as cnotify
from chat.views import send

OFFER = 'post:offer'
POST = 'post:post'
SOCIAL = 'post:social'
FEED = 'post:feed'

def feed(request):
    """
    This function displays a feed of offers and allows users to create new offers with associated
    topics.
    
    :param request: The request object represents the current HTTP request that the user has made to the
    server. It contains information about the user's request, such as the HTTP method used (GET, POST,
    etc.), any data submitted in the request, and the user's session information
    :return: an HTTP response that renders the 'post/feed.html' template with the context dictionary
    containing the 'offers', 'form', and 'form_t' variables.
    """
    offers = Offer.objects.filter(is_delete=False)
    if request.method == 'POST':
        form = OfferForm(request.POST, request.FILES)
        form_t = TopicForm(request.POST)
        if form.is_valid():
            offer = form.save(commit=False)
            offer.user = request.user
            if request.user.profile.strikes == 0:
                offer.save()
                create_topics(form_t, offer)
                for follower in request.user.profile.followers():
                    onotify(request, follower, offer.pk)
            return redirect(FEED)
    else:
        form = OfferForm()
        form_t = TopicForm()
    context = {'offers':offers, 'form':form, 'form_t':form_t}
    return render(request, 'post/feed.html', context)

def social(request):
    """
    This function displays posts and allows users to create new posts with topics and notifications.
    
    :param request: The request object represents the current HTTP request that the user has made to
    access the web application. It contains information about the user's request, such as the HTTP
    method used (GET, POST, etc.), the requested URL, any submitted data, and more
    :return: an HTTP response that renders the 'post/social.html' template with the context dictionary
    containing the 'posts', 'form', and 'form_t' variables.
    """
    posts = Post.objects.filter(is_delete=False)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        form_t = TopicForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            if request.user.profile.strikes == 0:
                post.save()
                create_topics(form_t, post)
                for follower in request.user.profile.followers():
                    notify(request, follower, post.pk)
            return redirect(SOCIAL)
    else:
        form = PostForm()
        form_t = TopicForm()
    context = {'posts':posts, 'form':form, 'form_t':form_t}
    return render(request, 'post/social.html', context)

@login_required
def delete(request, post_id):
    """
    This function deletes a post if the user who made the request is the same as the user who created
    the post.
    
    :param request: The request parameter is an object that represents the HTTP request made by the
    client to the server. It contains information such as the HTTP method used (GET, POST, etc.), the
    URL requested, any data submitted in the request, and more. In this specific function, the request
    parameter is used to
    :param post_id: The post_id parameter is the unique identifier of the post that the user wants to
    delete. It is used to retrieve the Post object from the database using the get() method of the Post
    model
    :return: a redirect to the `POST` view with the primary key (`pk`) of the deleted post as a
    parameter.
    """
    post = Post.objects.get(id=post_id)
    if post.user == request.user:
        post.is_delete = True
        post.save()
    return redirect(POST, post.pk)

@login_required
def odelete(request, offer_id):
    """
    This function deletes an offer if the user who created it is the one making the request.
    
    :param request: The request parameter is an object that represents the HTTP request made by the
    client to the server. It contains information such as the HTTP method used (GET, POST, etc.), the
    URL requested, any data submitted in the request, and more. In this function, the request parameter
    is used to determine
    :param offer_id: offer_id is a parameter that represents the unique identifier of an Offer object.
    It is used to retrieve the specific Offer object from the database using the get() method of the
    Offer model
    :return: a redirect to the `OFFER` page with the primary key (`pk`) of the deleted offer as a
    parameter.
    """
    offer = Offer.objects.get(id=offer_id)
    if offer.user == request.user:
        offer.is_delete = True
        offer.save()
    return redirect(OFFER, offer.pk)

@login_required
def like(request, pk):
    """
    This function allows a user to like or unlike a post, but only if they have less than or equal to 2
    strikes on their profile.
    
    :param request: The request parameter is an object that contains information about the current
    request, including the user making the request, the HTTP method used, and any data submitted with
    the request. It is typically passed to a view function in Django
    :param pk: pk is a parameter that stands for "primary key". In Django, primary keys are unique
    identifiers assigned to each instance of a model. In this case, pk is used to identify a specific
    Post object in the database
    :return: a redirect to the `POST` view with the primary key `pk` as a parameter.
    """
    post = Post.objects.get(pk=pk)
    is_like = False
    for like in post.likes.all():
        if like == request.user:
            is_like = True
            break
    if request.user.profile.strikes <= 2:
        if not is_like:
            post.likes.add(request.user)
        if is_like:
            post.likes.remove(request.user)
    return redirect(POST, pk)

@login_required
def olike(request, pk):
    """
    This function allows a user to like or unlike an offer, but only if they have less than or equal to
    2 strikes on their profile.
    
    :param request: The request parameter is an object that contains information about the current
    request, including the user making the request, the HTTP method used, and any data submitted with
    the request. It is typically passed to a view function in Django
    :param pk: pk is a parameter that represents the primary key of an Offer object. It is used to
    retrieve the specific Offer object from the database
    :return: a redirect to the OFFER page with the primary key (pk) of the offer that was just liked or
    unliked.
    """
    offer = Offer.objects.get(pk=pk)
    is_like = False
    for like in offer.likes.all():
        if like == request.user:
            is_like = True
            break
    if request.user.profile.strikes <= 2:
        if not is_like:
            offer.likes.add(request.user)
        if is_like:
            offer.likes.remove(request.user)
    return redirect(OFFER, pk)

def offer(request, pk):
    """
    The function checks if a user is blocked and redirects them if they are, otherwise it renders an
    offer page.
    
    :param request: The request parameter is an object that represents the HTTP request made by the
    client to the server. It contains information such as the HTTP method used (GET, POST, etc.), the
    URL requested, any data submitted in the request, and more. The view function uses this object to
    determine how to respond
    :param pk: pk stands for "primary key". In this context, it refers to the unique identifier of a
    specific Offer object in the database. The function retrieves the Offer object with the given
    primary key using the `Offer.objects.get(pk=pk)` method
    :return: If the user who created the offer is in the current user's blocking list or blocked list,
    the function will redirect to the FEED page. Otherwise, it will render the 'offer.html' template
    with the offer object passed in the context dictionary.
    """
    offer = Offer.objects.get(pk=pk)
    if offer.user in request.user.profile.blocking() or offer.user in request.user.profile.blocked():
        return redirect(FEED)
    else:
        context = {'offer':offer}
        return render(request, 'post/offer.html', context)

def post(request, pk):
    """
    This function handles the creation and display of comments on a post, with additional checks for
    blocked users.
    
    :param request: The HTTP request object that contains metadata about the request being made, such as
    the user agent, headers, and data
    :param pk: pk is a parameter that represents the primary key of a Post object. It is used to
    retrieve a specific Post object from the database
    :return: a HTTP response, either a redirect to the SOCIAL page if the post user is in the requesting
    user's blocking or blocked list, or a rendered HTML template with the post, comments, and forms for
    creating a new comment and topic.
    """
    post = Post.objects.get(pk=pk)
    if post.user in request.user.profile.blocking() or post.user in request.user.profile.blocked():
        return redirect(SOCIAL)
    else:
        if request.method == 'POST':
            form = PostForm(request.POST, request.FILES)
            form_t = TopicForm(request.POST)
            if form.is_valid():
                new_comment = form.save(commit=False)
                new_comment.user = request.user
                new_comment.comment = post
                if request.user.profile.strikes == 0:
                    new_comment.save()

app/templates/post/feed.html
{% extends 'app/layout.html' %}
{% load static %}
{% load humanize %}
{% load urlize_target_blank %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/input.css' %}" />
<h2 class="section__title">Feed</h2>
<br />
{% if user.profile.business %}
<div class="contact__container container grid">
  <div>
    <img class="testimonial__img" src="{{ user.profile.image.url }}" alt="" />
    <h3 class="contact__title">
      @{{ user.username }}
      <i class="uil uil-check-circle"></i>
    </h3>
    <span class="contact__subtitle"
      >{{ user.profile.bio|urlize_target_blank }}</span
    >
    <h3 class="contact__title">{{ user.offers.count }} Offers</h3>
    <h3 class="contact__title">{{ user.profile.followers.count }} Followers</h3>
    <h3 class="contact__title">{{ user.profile.following.count }} Following</h3>
  </div>
  {% if request.user.profile.strikes is 0 %}
  <form
    method="post"
    class="contact__form grid"
    ,
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    <div class="contact__content">{{ form.head }}</div>
    <div class="contact__content">
      {{ form.content }}
      <label class="hexagon__input_file">
        {{ form.image }}
        <i class="uil uil-image-plus"></i>
      </label>
      <img src="" alt="" id="preview_img" class="project__img" />
    </div>
    <div class="contact__content">{{ form_t.name }}</div>
    <input type="submit" value="Post" class="button button--flex" />
  </form>
  {% endif %}
</div>
<br />
{% endif %}
{% for offer in offers %}
{% if offer.user in request.user.profile.blocking %}
{% elif offer.user in request.user.profile.blocked %}
{% else %}
<div
  class="project__bg"
  id="{{ offer.pk }}"
  onclick="location.href='{% url 'post:feed' %}#{{ offer.pk }}'"
>
  <div class="project__container container grid">
    <div class="project__data">
      <a
        href="{% url 'bus' offer.user.username %}#{{ offer.pk }}"
        class="button button--flex button--white"
      >
        <img
          class="testimonial__img"
          src="{{ offer.user.profile.image.url }}"
          alt=""
        />
        <div class="button__icon">
          @{{ offer.user.username }}
          <i class="uil uil-check-circle"></i>
        </div>
      </a>
    </div>
    <time data-time="#" class="project__description">
      <i class="uil uil-clock"></i>
      {{ offer.timestamp|naturaltime }}
      <i class="uil uil-ellipsis-v button__icon services__button"></i>
      <div class="services__modal">
        <div class="services__modal-content">
          <h4 class="services__modal-title">
            Post
            <br />
            settings
          </h4>
          <i class="uil uil-times services__modal-close"></i>
          <ul class="services__modal-services grid">
            <li class="services__modal-service">
              <a
                href="{% url 'block' offer.user %}"
                class="button button--flex button--small button--link"
              >
                {% if request.user not in offer.user.profile.blocked %}
                Block
                {% else %}
                Unblock
                {% endif %}
              </a>
            </li>
            <li class="services__modal-service">
              <a
                href="{% url 'post:oreport' offer.pk %}"
                class="button button--flex button--small button--link"
              >
                Report
              </a>
            </li>
          </ul>
        </div>
      </div>
    </time>
    <div class="project__title">{{ offer.head|urlize_target_blank }}</div>
    <br />
    <p class="project__description">
      {{ offer.content|urlize_target_blank }}
      <br />
      {% if offer.image %}
      <img src="{{ offer.image.url }}" alt="" class="project__img" />
      {% endif %}
      <br />
      <a
        href="{% url 'post:olike' offer.pk %}"
        class="button button--flex button--white"
        style="font-size: 1.25rem"
      >
        {{ offer.likes.all.count }}
        {% if request.user in offer.likes.all %}
        <i class="uil uil-heart-break button__icon"></i>
        {% else %}
        <i class="uil uil-heart-alt button__icon"></i>
        {% endif %}
      </a>
      <a
        href="{% url 'post:apply' offer.pk %}"
        class="button button--flex button--white"
        style="font-size: 1.25rem"
      >
        <i class="uil uil-comments button__icon"></i>
      </a>
      {% if offer.user == request.user %}
      <a
        href="{% url 'post:odelete' offer.pk %}"
        class="button button--flex button--white"
        style="font-size: 1.25rem"
      >
        <i class="uil uil-trash-alt button__icon"></i>
      </a>
      {% endif %}
      <br />
      <br />
      {% if offer.topics.all %}
      Topics:
      {% for Topic in offer.topics.all %}
      <a
        href="{% url 'post:otopic' Topic %}"
        class="button button--flex button--white"
      >
        #{{ Topic.name }}
      </a>
      {% endfor %}
      {% endif %}
    </p>
  </div>
</div>
<br />
{% endif %}
{% endfor %}
<script src="{% static 'js/input.js' %}"></script>
{% endblock %}

app/templates/post/topic.html
{% extends 'app/layout.html' %}
{% load static %}
{% load humanize %}
{% load urlize_target_blank %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/input.css' %}" />
<h2 class="section__title">Topic</h2>
<span class="section__subtitle">{{ topic }}</span>
{% for post in posts %}
{% if post.user in request.user.profile.blocking %}
{% elif post.user in request.user.profile.blocked %}
{% else %}
<div
  class="project__bg"
  id="{{ post.pk }}"
  onclick="location.href='{% url 'post:social' %}#{{ post.pk }}'"
>
  <div class="project__container container grid">
    <div class="project__data">
      <a
        href="{% url 'profile' post.user.username %}#{{ post.pk }}"
        class="button button--flex button--white"
      >
        <img class="testimonial__img" src="{{ post.user.profile.image.url }}" alt="" />
        <div class="button__icon">
          @{{ post.user.username }}
          {% if post.user.is_superuser %}
          <i class="uil uil-polygon"></i>
          {% elif post.user.is_staff %}
          <i class="uil uil-wrench"></i>
          {% elif post.user.profile.business %}
          <i class="uil uil-check-circle"></i>
          {% endif %}
        </div>
      </a>
    </div>
    <time data-time="#" class="project__description">
      <i class="uil uil-clock"></i>
      {{ post.timestamp|naturaltime }}
    </time>
    <p class="project__description">
      {{ post.content|urlize_target_blank }}
      <br />
      {% if post.image %}
      <img src="{{ post.image.url }}" alt="" class="project__img" />
      {% endif %}
      <br />
      <a
        href="{% url 'post:like' post.pk %}"
        class="button button--flex button--white"
        style="font-size: 1.25rem"
      >
        {{ post.likes.all.count }}
        {% if request.user in post.likes.all %}
        <i class="uil uil-heart-break button__icon"></i>
        {% else %}
        <i class="uil uil-heart-alt button__icon"></i>
        {% endif %}
      </a>
      <a
        href="{% url 'post:post' post.pk %}#comments"
        class="button button--flex button--white"
        style="font-size: 1.25rem"
      >
        <i class="uil uil-comments button__icon"></i>
      </a>
      {% if post.user == request.user %}
      <a
        href="{% url 'post:delete' post.pk %}"
        class="button button--flex button--white"
        style="font-size: 1.25rem"
      >
        <i class="uil uil-trash-alt button__icon"></i>
      </a>
      {% endif %}
      <br />
      <br />
      {% if post.topics.all %}
      Topics:
      {% for Topic in post.topics.all %}
      <a
        href="{% url 'post:topic' Topic %}"
        class="button button--flex button--white"
      >
        #{{ Topic.name }}
      </a>
      {% endfor %}
      {% endif %}
    </p>
    <br />
  </div>
</div>
<br />
{% endif %}
{% endfor %}
{% for offer in offers %}
{% if offer.user in request.user.profile.blocking %}
{% elif offer.user in request.user.profile.blocked %}
{% else %}
<div
  class="project__bg"
  id="{{ offer.pk }}"
  onclick="location.href='{% url 'post:feed' %}#{{ offer.pk }}'"
>
  <div class="project__container container grid">
    <div class="project__data">
      <a
        href="{% url 'bus' offer.user.username %}#{{ offer.pk }}"
        class="button button--flex button--white"
      >
        <img
          class="testimonial__img"
          src="{{ offer.user.profile.image.url }}"
          alt=""
        />
        <div class="button__icon">
          @{{ offer.user.username }}
          <i class="uil uil-check-circle"></i>
        </div>
      </a>
    </div>
    <time data-time="#" class="project__description">
      <i class="uil uil-clock"></i>
      {{ offer.timestamp|naturaltime }}
    </time>
    <div class="project__title">{{ offer.head|urlize_target_blank }}</div>
    <br />
    <p class="project__description">
      {{ offer.content|urlize_target_blank }}
      <br />
      {% if offer.image %}
      <img src="{{ offer.image.url }}" alt="" class="project__img" />
      {% endif %}
      <br />
      <a
        href="{% url 'post:olike' offer.pk %}"
        class="button button--flex button--white"
        style="font-size: 1.25rem"
      >
        {{ offer.likes.all.count }}
        {% if request.user in offer.likes.all %}
        <i class="uil uil-heart-break button__icon"></i>
        {% else %}
        <i class="uil uil-heart-alt button__icon"></i>
        {% endif %}
      </a>
      <a
        href="{% url 'chat:inbox' offer.user %}"
        class="button button--flex button--white"
        style="font-size: 1.25rem"
      >
        <i class="uil uil-comments button__icon"></i>
      </a>
      {% if offer.user == request.user %}
      <a
        href="{% url 'post:odelete' offer.pk %}"
        class="button button--flex button--white"
        style="font-size: 1.25rem"
      >
        <i class="uil uil-trash-alt button__icon"></i>
      </a>
      {% endif %}
      <br />
      <br />
      {% if offer.topics.all %}
      Topics:
      {% for Topic in offer.topics.all %}
      <a
        href="{% url 'post:otopic' Topic %}"
        class="button button--flex button--white"
      >
        #{{ Topic.name }}
      </a>
      {% endfor %}
      {% endif %}
    </p>
  </div>
</div>
<br />
{% endif %}
{% endfor %}
{% endblock %}