app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(template_name='app/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('@<str:username>/', views.bus, name='bus'),
    path('u/<str:username>/', views.profile, name='profile'),
    path('edit/', views.edit, name='edit'),
    path('@<str:username>/follow/', views.follow, name='follow'),
    path('about/start/register/', views.registerb, name='registerb'),
    path('about/start/', views.startb, name='startb'),
    path('@<str:username>/report/', views.report, name='report'),
    path('about/staff/', views.staff, name='staff'),
    path('@<str:username>/block/', views.block, name='block'),
    path('about/', views.about, name='about'),
]

chat/urls.py
from django.urls import path
from .views import InboxView, UserListsView, MessagesListView, report

app_name = 'chat'

urlpatterns = [
    path('', MessagesListView.as_view(), name='message_list'),
    path('u/', UserListsView.as_view(), name='users_list'),
    path('u/<str:username>/', InboxView.as_view(), name='inbox'),
    path('u/<str:username>/report/', report, name='report'),
]

hexagon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('chat/', include('chat.urls')),
    path('', include('post.urls')),
    path('staff/', include('staff.urls')),
    path('verification/', include('verify_email.urls')),
    path('notifications/', include('notifications.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'

urlpatterns = [
    path('mailverify/', views.mailverify, name='mailverify'),
    path('', views.notifications, name='list'),
    path('strikes/', views.strikes, name='strikes'),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('feed/', views.feed, name='feed'),
    path('social/', views.social, name='social'),
    path('feed/<int:offer_id>/delete/', views.odelete, name='odelete'),
    path('social/<int:post_id>/delete/', views.delete, name='delete'),
    path('feed/<int:pk>/like/', views.olike, name='olike'),
    path('social/<int:pk>/like/', views.like, name='like'),
    path('feed/<int:pk>/', views.offer, name='offer'),
    path('social/<int:pk>/', views.post, name='post'),
    path('social/topic/<str:name>', views.topics, name='topic'),
    path('feed/topic/<str:name>', views.otopics, name='otopic'),
    path('social/<int:pk>/report/', views.report, name='report'),
    path('feed/<int:pk>/report/', views.oreport, name='oreport'),
    path('feed/<int:pk>/apply/', views.apply, name='apply'),
]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('', views.home, name='home'),
    path('feed/', views.feed, name='feed'),
    path('feed/<int:pk>/', views.offer, name='offer'),
    path('feed/<int:pk>/save/', views.osave, name='osave'),
    path('feed/<int:pk>/delete/', views.odelete, name='odelete'),
    path('social/', views.social, name='social'),
    path('social/<int:pk>/', views.post, name='post'),
    path('social/<int:pk>/save/', views.psave, name='psave'),
    path('social/<int:pk>/delete/', views.pdelete, name='pdelete'),
    path('chat/', views.chat, name='chat'),
    path('chat/<int:pk>/', views.inbox, name='inbox'),
    path('chat/<int:pk>/strike/', views.cstrike, name='cstrike'),
    path('chat/<int:pk>/dismiss/', views.cdismiss, name='cdismiss'),
    path('user/', views.user, name='user'),
    path('user/<int:pk>/', views.bus, name='bus'),
    path('user/<int:pk>/u/', views.profile, name='profile'),
    path('user/<int:pk>/strike/', views.ustrike, name='ustrike'),
    path('user/<int:pk>/dismiss/', views.udismiss, name='udismiss'),
    path('business/', views.blist, name='blist'),
    path('business/<int:pk>/', views.bprofile, name='bprofile'),
    path('business/<int:pk>/accept', views.baccept, name='baccept'),
    path('business/<int:pk>/deny', views.bdeny, name='bdeny'),
    path('staff/', views.slist, name='slist'),
    path('staff/<int:pk>/', views.sprofile, name='sprofile'),
    path('staff/<int:pk>/accept', views.saccept, name='saccept'),
    path('staff/<int:pk>/deny', views.sdeny, name='sdeny'),
]

app/templates/app/bus.html
{% extends 'post/feed.html' %}
{% load humanize %}
{% load urlize_target_blank %}
{% block content %}
<h2 class="section__title">Profile</h2>
<br />
<div class="about__container container grid">
  <div>
    <img class="testimonial__img" src="{{ user.profile.image.url }}" alt="" />
    <h3 class="contact__title">
      <a
        class="button button--flex"
        href="{{ user.profile.domain }}"
        target="_blank"
        >@{{ user.username }}</a
      >
      <a href="{% url 'profile' user %}" style="color: var(--first-color)">
        <i class="uil uil-check-circle"></i>
      </a>
      <a
        href="{% url 'chat:inbox' user %}"
        class="button button--flex button--small button--link"
      >
        <i class="uil uil-chat button__icon"></i>
      </a>
      <span
        class="button button--flex button--small button--link services__button"
      >
        <i class="uil uil-info-circle button__icon"></i>
      </span>
      <div class="services__modal">
        <div class="services__modal-content">
          <h4 class="services__modal-title">
            User
            <br />
            settings
          </h4>
          <i class="uil uil-times services__modal-close"></i>
          <ul class="services__modal-services grid">
            <li class="services__modal-service">
              <a
                href="{% url 'block' user %}"
                class="button button--flex button--small button--link"
              >
                {% if request.user not in user.profile.blocked %}
                Block
                {% else%}
                Unblock
                {% endif %}
              </a>
            </li>
            <li class="services__modal-service">
              <a
                href="{% url 'report' user %}"
                class="button button--flex button--small button--link"
              >
                Report
              </a>
            </li>
          </ul>
        </div>
      </div>
    </h3>
    <span class="contact__subtitle"
      >{{ user.profile.bio|urlize_target_blank }}</span
    >
    {% if request.user.is_authenticated %}
    <br />
    <br />
    {% if user.username != request.user.username %}
    {% if user not in request.user.profile.following %}
    <a class="button button--flex" href="{% url 'follow' user %}">Follow</a>
    {% else %}
    <a class="button button--flex" href="{% url 'unfollow' user %}">Unfollow</a>
    {% endif %}
    {% else %}
    <a class="button button--flex" href="{% url 'edit' %}">Edit</a>
    {% endif %}
    {% endif %}
    <h3 class="contact__title">{{ user.offers.count }} Offers</h3>
    <h3 class="contact__title">{{ user.profile.followers.count }} Followers</h3>
    <h3 class="contact__title">{{ user.profile.following.count }} Following</h3>
  </div>
  <div>
    {% for offer in offers %}
    <div
      class="project__bg"
      id="{{ offer.pk }}"
      onclick="location.href='{% url 'bus' user.username %}#{{ offer.pk }}'"
    >
      <div class="project__container container grid">
        <time data-time="#" class="project__description">
          <i class="uil uil-clock"></i>
          {{ offer.timestamp|naturaltime }}
          <i class="uil uil-ellipsis-v button__icon services__button"></i>
          <div class="services__modal">
            <div class="services__modal-content">
              <h4 class="services__modal-title">
                Post
                <br />
                settings
              </h4>
              <i class="uil uil-times services__modal-close"></i>
              <ul class="services__modal-services grid">
                <li class="services__modal-service">
                  <a
                    href="{% url 'post:oreport' offer.pk %}"
                    class="button button--flex button--small button--link"
                  >
                    Report
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </time>
        <br />
        <div class="project__title">{{ offer.head|urlize_target_blank }}</div>
        <br />
        <p class="project__description">
          {{ offer.content|urlize_target_blank }}
          {% if offer.topics.all %}
          {% for Topic in offer.topics.all %}
          #{{ Topic.name }}
          {% endfor %}
          {% endif %}
          <br />
          {% if offer.image %}
          <img src="{{ offer.image.url }}" alt="" class="project__img" />
          {% endif %}
          <br />
          <a
            href="{% url 'post:olike' offer.pk %}"
            class="button button--flex button--white"
            style="font-size: 1.25rem"
          >
            {{ offer.likes.all.count }}
            {% if request.user in offer.likes.all %}
            <i class="uil uil-heart-break button__icon"></i>
            {% else %}
            <i class="uil uil-heart-alt button__icon"></i>
            {% endif %}
          </a>
          <a
            href="{% url 'post:apply' offer.pk %}"
            class="button button--flex button--white"
            style="font-size: 1.25rem"
          >
            <i class="uil uil-comments button__icon"></i>
          </a>
          {% if offer.user == request.user %}
          <a
            href="{% url 'post:odelete' offer.pk %}"
            class="button button--flex button--white"
            style="font-size: 1.25rem"
          >
            <i class="uil uil-trash-alt button__icon"></i>
          </a>
          {% endif %}
        </p>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

app/templates/app/edit.html
{% extends 'app/layout.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/input.css' %}" />
<h2 class="section__title">Edit</h2>
<br />
<div class="container grid">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="contact__inputs grid">
      <div class="contact__content">
        <label class="contact__labe">Biography</label>
        <input type="text" value="{{ request.user.profile.bio }}" name="bio" />
      </div>
      <div class="contact__content">
        <label class="contact__labe hexagon__input_file">
          {{ form.cv }}
          {{ form.error.cv }}
          <i class="uil uil-file-upload-alt"></i>
        </label>
        <img src="" alt="" id="preview_pdf" class="project__img" />
      </div>
      <div class="contact__content">
        <label class="contact__labe hexagon__input_file">
          {{ form.image }}
          {{ form.error.image }}
          <i class="uil uil-image-plus"></i>
        </label>
        <img
          src="{{ user.profile.image.url }}"
          alt=""
          id="preview_img"
          class="project__img"
        />
      </div>
      <button class="button button--flex">Edit</button>
    </div>
  </form>
</div>
<script src="{% static 'js/input.js' %}"></script>
{% endblock %}

app/templates/app/home.html
{% extends 'app/layout.html' %}
{% load static %}
{% block content %}
<div class="home__container container grid" id="home">
  <div class="home__content grid">
    <div class="home__img">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        version="1.1"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        xmlns:svgjs="http://svgjs.dev/svgjs"
        viewBox="0 0 120 120"
        class="home__blob"
      >
        <svg
          viewBox="0 0 120.98604583740234 138.99368286132812"
        >
          <svg
            viewBox="0 0 121 134"
            xmlns="http://www.w3.org/2000/svg"
          >
            <g clip-path="url(#clip0)">
              <path
                d="M112.526 27.3193L68.9608 2.25675C63.727 -0.756156 57.2594 -0.756156 52.0257 2.25675L8.46078 27.3193C3.22703 30.3322 0 35.9121 0 41.9379V92.063C0 98.0888 3.22703 103.669 8.46078 106.682L52.0257 131.731C57.2594 134.744 63.727 134.744 68.9608 131.731L112.526 106.668C117.759 103.655 120.986 98.0888 120.986 92.0495V41.9244C121 35.9121 117.759 30.3322 112.526 27.3193ZM105.841 83.335C105.841 89.3608 102.614 94.9408 97.3803 97.9537L68.9608 114.288C63.727 117.301 57.2594 117.301 52.0257 114.288L23.6197 97.9537C18.3859 94.9408 15.1589 89.3743 15.1589 83.335V50.6524C15.1589 44.6266 18.3859 39.0466 23.6197 36.0337L52.0257 19.6992C57.2594 16.6863 63.727 16.6863 68.9608 19.6992L97.3668 36.0337C102.601 39.0466 105.828 44.6131 105.828 50.6524V83.335H105.841Z"
              ></path>
              <path
                d="M91.9027 73.7147V60.285C91.9027 53.2594 88.1469 46.7607 82.0318 43.2479L70.3575 36.533C64.256 33.0202 56.7308 33.0202 50.6157 36.533L38.9415 43.2479C32.8399 46.7607 29.0706 53.2594 29.0706 60.285V73.7147C29.0706 80.7403 32.8264 87.239 38.9415 90.7518L50.6157 97.4667C56.7172 100.979 64.2425 100.979 70.3575 97.4667L82.0318 90.7518C88.1469 87.2255 91.9027 80.7403 91.9027 73.7147Z"
              ></path>
            </g>
          </svg>
        </svg>
      </svg>
    </div>
    <div class="home__data">
      <h1 class="home__title">Hexagon</h1>
      <h3 class="home__subtitle">Project</h3>
      <p class="home__description">P-TECH</p>
      <a href="{% url 'post:feed' %}" class="button button--flex">
        Feed
        <i class="uil uil-message"></i>
      </a>
    </div>
  </div>
  <div class="home__scroll">
    <a
      href="{% url 'about' %}#businesses"
      class="home__scroll-button button--flex"
    >
      <i class="uil uil-mouse-alt home__scroll-mouse"></i>
      <span class="home__scroll-name">For businesses</span>
      <i class="uil uil-arrow-down home__scroll-arrow"></i>
    </a>
  </div>
</div>
{% endblock %}

app/templates/app/layout.html
<!--
                     .                    .                           
                :-:--=:-:::.             :=-**##*=:                   
                 :=----------.         .-%@@@@@@@@@%:                 
                :-------------:        :@@@@@@@@@@@@%.                
               :-=-----------==:       +@@@@@@@@@@@@@#                
             .------------=------.     =@@@@@@@@@@@@@#                
              :=-=-------===-=--      .+%@@@@@@@@@@@#=                
               --=--------==-=-.       -*%@@@@@@@@@*-.                
                  ::----===+-             .#%@@@@*.                   
                     -+++=: .               :+##+                     
                    -+=====.              .=%@@%%%#=                  
                 :-----------:.        :+#%%%@@@@@%@%+-               
               -----------------      -%%%%%@@@%@@%%@%%*              
              .-==----------==--:     #%%%@%@@@@@@@@@@%%.             
              :-=+----------*=---    =%%%@@%%@@@%%@@@%%%=             
              ---=----------*----:  .#%%%@@%%@@@%@%@@%%%%             
             :-===----------+=---=  -#%%%@@%%@%@%@%@@%%%%=            
               --=----------=#==+.   ==+%@@%%@@@%@%@@*++.             
               --=-----------*=---  :===#@@%%@@@%@%%%--=              
               -==-----------++--=  ---:#@%@@@%%%@@@%--=              
               -=------------=:--=. =-- %@%%%%%%@%%%@=-=              
              .-+-------------.:---.--: %%%%%%%%@%%@@+==              
              :-++*++++++*+***. --=+--  *###########**-=              
              --*+++++++++*+++: :--*-: :------=------*-=              
              =-*++++++++*+***- .--*-. :-------------+-=              
             .--*+++=+*++*+***+ :==*=: -------=------===:             
             :=+++++==+++*++**+ -*++=. -------+-------+=:             
              -++++=+==**+++***  :-:   -------+-------+.              
               -+++=++=****+**#        -------+=------=               
               .++==*=---=*+**+        =------+*------=               
                ----=    :---=          ====-.::+====                 
           :**#==---=:   ----= ..   .:::=--=+*%#*--=+***. .--:..      
           .=+**#=--==   :=--=%@*:.-=+%%*--=: ::+=--+***+=#@%*-=-::.  
               :+=--=. :::=--=:.-*#%*--=*---+-+**=--=--=+**+*=**%@%=  
                 =--= .#%%=--=.  +*#%#= +---#%++#=---.+%@%+  .+++*+-  
                 ====   .:+===:   -==+= :===*+: -==== .--:.      ..   
                 =--=     ----:         .----   :=---                 
                 ----     :---:         .=---   .=---                 
                 ----     :---:         .=---    =---                 
                 ---:     :---:         .=---    +---                 
                 +##%.    =*##-         -%%#:    %%%#                 
                :@@@@-    #@@@+         %@@@*   :@@@%:                
                .====.    -++=:         =+==-    --==.                
@milosnowcat
-->
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!--==================== UNICONS ====================-->
    <link
      rel="stylesheet"
      href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
    />
    <!--==================== SWIPER CSS ====================-->
    <link
      rel="stylesheet"
      href="https://www.rahcode.com/assets/css/swiper-bundle.min.css"
    />
    <!--==================== CSS ====================-->
    <link
      rel="stylesheet"
      href="https://www.rahcode.com/assets/css/styles.css"
    />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon_transparent_32x32.png' %}"
    />
    <title>Hexagon</title>
  </head>
  <body>
    <!--==================== HEADER ====================-->
    <header class="header" id="header">
      <nav class="nav container">
        <a href="{% url 'home' %}" class="nav__logo">Hexagon</a>
        <div class="nav__menu" id="nav-menu">
          <ul class="nav__list grid">
            <li class="nav__item">
              <a href="{% url 'post:feed' %}" class="nav__link">
                <i class="uil uil-bag-alt nav__icon"></i>
                Feed
              </a>
            </li>
            <li class="nav__item">
              <a href="{% url 'post:social' %}" class="nav__link">
                <i class="uil uil-globe nav__icon"></i>
                Social
              </a>
            </li>
            <li class="nav__item">
              <a href="{% url 'chat:message_list' %}" class="nav__link">
                <i class="uil uil-chat nav__icon"></i>
                Chat
              </a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav__item">
              <a href="{% url 'bus' request.user %}" class="nav__link">
                <i class="uil uil-user-circle nav__icon"></i>
                @{{ request.user }}
              </a>
            </li>
            {% if request.user.is_staff %}
            <li class="nav__item">
              <a href="{% url 'staff:home' %}" class="nav__link">
                <i class="uil uil-wrench nav__icon"></i>
                Staff
              </a>
            </li>
            {% endif %}
            <li class="nav__item">
              <a href="{% url 'logout' %}" class="nav__link">
                <i class="uil uil-sign-out-alt nav__icon"></i>
                Logout
              </a>
            </li>
            {% else %}
            <li class="nav__item">
              <a href="{% url 'register' %}" class="nav__link">
                <i class="uil uil-power nav__icon"></i>
                Register
              </a>
            </li>
            <li class="nav__item">
              <a href="{% url 'login' %}" class="nav__link">
                <i class="uil uil-sign-in-alt nav__icon"></i>
                Login
              </a>
            </li>
            {% endif %}
          </ul>
          <i class="uil uil-times nav__close" id="nav-close"></i>
        </div>
        <div class="nav__btns">
          <a href="{% url 'notifications:list' %}" class="nav__link">
            <i class="uil uil-bell change-theme"></i>
          </a>
          <!-- Theme change button -->
          <i class="uil uil-moon change-theme" id="theme-button"></i>
          <div class="nav__toggle" id="nav-toggle">
            <i class="uil uil-apps"></i>
          </div>
        </div>
      </nav>
    </header>
    <!--==================== MAIN ====================-->
    <main class="main">
      <section class="section">
        {% if msgs %}
        {% for msg in msgs %}
        <div class="button button--flex {{ message.tags }}">{{ msg }}</div>
        {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock content %}
      </section>
    </main>
    <!--==================== FOOTER ====================-->
    <footer class="footer" id="foot"></footer>
    <!--==================== SCROLL TOP ====================-->
    <a href="#" class="scrollup" id="scroll-up">
      <i class="uil uil-arrow-up scrollup__icon"></i>
    </a>
    <!--==================== SWIPER JS ====================-->
    <script src="https://www.rahcode.com/assets/js/swiper-bundle.min.js"></script>
    <!--==================== MAIN JS ====================-->
    <script
      src="https://www.rahcode.com/assets/js/main.js"
      type="module"
    ></script>
  </body>
</html>

app/templates/app/login.html
{% extends 'app/layout.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/input.css' %}" />
<h2 class="section__title">Login</h2>
<br />
<div class="container grid">
  <form method="post">
    {% csrf_token %}
    <div class="contact__inputs grid">
      <div class="contact__content">
        <label for="" class="contact__labe">Username</label>
        {{ form.username }}
      </div>
      <div class="contact__content">
        <label for="" class="contact__labe">Password</label>
        {{ form.password }}
      </div>
      <button class="button button--flex">Login</button>
    </div>
  </form>
  <a href="{% url 'register' %}">Don't have an account yet?</a>
  <a href="{% url 'notifications:mailverify' %}"
    >You didn't receive your verification email?</a
  >
</div>
{% endblock %}

app/templates/app/profile.html
{% extends 'post/feed.html' %}
{% load humanize %}
{% load urlize_target_blank %}
{% block content %}
<h2 class="section__title">Profile</h2>
<br />
<div class="about__container container grid">
  <div>
    <img class="testimonial__img" src="{{ user.profile.image.url }}" alt="" />
    <h3 class="contact__title">
      @{{ user.username }}
      {% if user.is_superuser %}
      <i class="uil uil-polygon"></i>
      {% elif user.is_staff %}
      <i class="uil uil-wrench"></i>
      {% elif user.profile.business %}
      <a href="{% url 'bus' user %}" style="color: var(--first-color)">
        <i class="uil uil-check-circle"></i>
      </a>
      {% endif %}
      <a
        href="{% url 'chat:inbox' user %}"
        class="button button--flex button--small button--link"
      >
        <i class="uil uil-chat button__icon"></i>
      </a>
      <span
        class="button button--flex button--small button--link services__button"
      >
        <i class="uil uil-info-circle button__icon"></i>
      </span>
      <div class="services__modal">
        <div class="services__modal-content">
          <h4 class="services__modal-title">
            User
            <br />
            settings
          </h4>
          <i class="uil uil-times services__modal-close"></i>

          <ul class="services__modal-services grid">
            <li class="services__modal-service">
              <a
                href="{% url 'block' user %}"
                class="button button--flex button--small button--link"
              >
                {% if request.user not in user.profile.blocked %}
                Block
                {% else %}
                Unblock
                {% endif %}
              </a>
            </li>
            <li class="services__modal-service">
              <a
                href="{% url 'report' user %}"
                class="button button--flex button--small button--link"
              >
                Report
              </a>
            </li>
          </ul>
        </div>
      </div>
    </h3>
    <span class="contact__subtitle"
      >{{ user.profile.bio|urlize_target_blank }}</span
    >
    {% if request.user.is_authenticated %}
    <br />
    <br />
    {% if request.user.profile.business or request.user.is_staff %}
    <div class="about__buttons">
      <a
        download="{{ user.username }}"
        href="{{ user.profile.cv.url }}"
        class="button button--flex"
      >
        CV
        <i class="uil uil-download-alt button__icon"></i>
      </a>
    </div>
    <br />
    <br />
    {% endif %}
    {% if user.username != request.user.username %}
    <a class="button button--flex" href="{% url 'follow' user %}">
      {% if user not in request.user.profile.following %}
      Follow
      {% else %}
      Unfollow
      {% endif %}
    </a>
    {% else %}
    <a class="button button--flex" href="{% url 'edit' %}">Edit</a>
    {% endif %}
    {% endif %}
    <h3 class="contact__title">{{ user.posts.count }} Post</h3>
    <h3 class="contact__title">{{ user.profile.followers.count }} Followers</h3>
    <h3 class="contact__title">{{ user.profile.following.count }} Following</h3>
  </div>
  <div>
    {% for post in posts %}
    <div
      class="project__bg"
      id="{{ post.pk }}"
      onclick="location.href='{% url 'profile' user.username %}#{{ post.pk }}'"
    >
      <div class="project__container container grid">
        <time data-time="#" class="project__description">
          <i class="uil uil-clock"></i>
          {{ post.timestamp|naturaltime }}
          <i class="uil uil-ellipsis-v button__icon services__button"></i>

          <div class="services__modal">
            <div class="services__modal-content">
              <h4 class="services__modal-title">
                Post
                <br />
                settings
              </h4>
              <i class="uil uil-times services__modal-close"></i>

              <ul class="services__modal-services grid">
                <li class="services__modal-service">
                  <a
                    href="{% url 'post:report' post.pk %}"
                    class="button button--flex button--small button--link"
                  >
                    Report
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </time>
        <br />
        <p class="project__description">
          {{ post.content|urlize_target_blank }}
          {% if post.topics.all %}
          {% for Topic in post.topics.all %}
          #{{ Topic.name }}
          {% endfor %}
          {% endif %}
          <br />
          {% if post.image %}
          <img src="{{ post.image.url }}" alt="" class="project__img" />
          {% endif %}
          <br />
          <a
            href="{% url 'post:like' post.pk %}"
            class="button button--flex button--white"
            style="font-size: 1.25rem"
          >
            {{ post.likes.all.count }}
            {% if request.user in post.likes.all %}
            <i class="uil uil-heart-break button__icon"></i>
            {% else %}
            <i class="uil uil-heart-alt button__icon"></i>
            {% endif %}
          </a>
          <a
            href="{% url 'post:post' post.pk %}#comments"
            class="button button--flex button--white"
            style="font-size: 1.25rem"
          >
            <i class="uil uil-comments button__icon"></i>
          </a>
          {% if post.user == request.user %}
          <a
            href="{% url 'post:delete' post.pk %}"
            class="button button--flex button--white"
            style="font-size: 1.25rem"
          >
            <i class="uil uil-trash-alt button__icon"></i>
          </a>
          {% endif %}
        </p>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

app/templates/app/register.html
{% extends 'app/layout.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/input.css' %}" />
<h2 class="section__title">Register</h2>
<br />
<div class="container grid">
  <form method="post">
    {% csrf_token %}
    <div class="contact__inputs grid">
      <div class="contact__content">
        <label for="" class="contact__labe">First name</label>
        {{ form.first_name }}
      </div>
      <div class="contact__content">
        <label for="" class="contact__labe">Last name</label>
        {{ form.last_name }}
      </div>
      <div class="contact__content">
        <label for="" class="contact__labe">Username</label>
        {{ form.username }}
        {{ form.errors.username }}
      </div>
      <div class="contact__content">
        <label for="" class="contact__labe">Email</label>
        {{ form.email }}
        {{ form.errors.email }}
      </div>
      <div class="contact__content">
        <label for="" class="contact__labe">Password</label>
        {{ form.password1 }}
        {{ form.errors.password1 }}
      </div>
      <div class="contact__content">
        <label for="" class="contact__labe">Confirm password</label>
        {{ form.password2 }}
        {{ form.errors.password2 }}
      </div>
      <div class="contact__content">
        <input type="checkbox" required />
        I accept the
        <a href="{% url 'about' %}#terms" target="_blank"
          >Terms and Conditions</a
        >
        in addition to the
        <a href="{% url 'about' %}#privacy" target="_blank">Privacy Notice</a>
      </div>
      <button class="button button--flex">Register</button>
    </div>
  </form>
</div>
{% endblock %}

app/templates/app/startB.html
{% extends 'app/layout.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/input.css' %}" />
<h2 class="section__title">Start</h2>
<br />
<div class="container grid">
  <form method="post">
    {% csrf_token %}
    <div class="contact__inputs grid">
      {{ form.business }}
      <div class="contact__content">
        <label for="" class="contact__labe">Web page</label>
        {{ form.domain }}
      </div>
      <button class="button button--flex">Register</button>
    </div>
  </form>
</div>
{% endblock %}